# Generated by Django 4.2 on 2023-04-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=150)),
                ('apellidoPaciente', models.CharField(max_length=150)),
                ('CI', models.CharField(max_length=12)),
                ('fechaNaciemiento', models.DateField(null=True)),
                ('direccionPaciente', models.TextField()),
                ('numeroTelefonico', models.CharField(max_length=11)),
            ],
        ),
    ]
