# Generated by Django 4.2 on 2023-05-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombrePaciente',
            field=models.CharField(max_length=150, verbose_name='Nombre Paciente'),
        ),
    ]
